from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def run_python(code: str, env: dict[str, str]) -> subprocess.CompletedProcess[str]:
    merged = os.environ.copy()
    merged.update(env)
    merged["PYTHONPATH"] = str(ROOT / "scripts")
    return subprocess.run([sys.executable, "-c", code], cwd=ROOT, env=merged, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def write_compatible_stage4_resources(charmm: Path, membrane: Path, release: str = "November 2018") -> None:
    charmm.mkdir()
    membrane.mkdir()
    for name in ("forcefield.itp", "ffbonded.itp", "ffnonbonded.itp", "merged.rtp", "tip3p.itp", "ions.itp"):
        (charmm / name).write_text(f"; fake test {name}\n", encoding="utf-8")
    (charmm / "forcefield.doc").write_text(
        f"CHARMM36 all-atom force field ({release})\nParameters taken from CHARMM36 and CGenFF 4.1\n",
        encoding="utf-8",
    )
    (charmm / "forcefield.itp").write_text("; generated by charmm2gmx.py\n", encoding="utf-8")
    (charmm / "merged.n.tdb").write_text("[ None ]\n[ ACE ]\n", encoding="utf-8")
    (charmm / "merged.c.tdb").write_text("[ None ]\n[ CT3 ]\n", encoding="utf-8")
    (membrane / "forcefield.itp").write_text(";; Generated by CHARMM-GUI FF-Converter\n", encoding="utf-8")
    (membrane / "top_all36_prot.rtf").write_text(
        f"*>>>>>>>>>>>>>>>>>>>>>>>>>> {release} <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\nPRES ACE 0.00\nPRES CT3 0.00\n",
        encoding="utf-8",
    )
    (membrane / "par_all36m_prot.prm").write_text(
        f"*>>>>>>>>>>>>>>>>>>>>>>>>>> {release} <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n! CHARMM36m\n",
        encoding="utf-8",
    )


def test_dssp_detection_through_dssp_bin(tmp_path: Path) -> None:
    exe = tmp_path / "mkdssp"
    exe.write_text("#!/bin/sh\necho mkdssp-test\n", encoding="utf-8")
    exe.chmod(0o755)
    result = run_python("from external_dependencies import resolve_dssp; print(resolve_dssp(required=True).status)", {"DSSP_BIN": str(exe)})
    assert result.returncode == 0, result.stderr
    assert "PASS" in result.stdout


def test_missing_required_dssp_fails(tmp_path: Path) -> None:
    result = run_python("from external_dependencies import resolve_dssp; resolve_dssp(required=True)", {"DSSP_BIN": str(tmp_path / "missing")})
    assert result.returncode != 0
    assert "DSSP" in result.stderr


def test_pyrosetta_import_through_configured_python(tmp_path: Path) -> None:
    py = tmp_path / "fake_py"
    py.write_text("#!/bin/sh\necho '{\"version\":\"fake-pyrosetta\"}'\n", encoding="utf-8")
    py.chmod(0o755)
    result = run_python("from external_dependencies import resolve_pyrosetta; print(resolve_pyrosetta(required=True).version)", {"PYROSETTA_PYTHON": str(py)})
    assert result.returncode == 0, result.stderr
    assert "fake-pyrosetta" in result.stdout


def test_missing_pyrosetta_only_blocks_pyrosetta_mode(tmp_path: Path) -> None:
    code = """
from membraneforger_workflow import load_config, check_stage4
from pathlib import Path
cfg = load_config(Path('config/workflow.example.yaml'))
print(check_stage4(cfg, 'minimal'))
cfg['stage4']['pyrosetta_plugins_enabled'] = True
print(check_stage4(cfg, 'pyro'))
"""
    result = run_python(code, {"PYROSETTA_PYTHON": str(tmp_path / "missing")})
    assert result.returncode == 0, result.stderr
    lines = result.stdout.splitlines()
    assert lines[0] == "[]"
    assert "PyRosetta is required" in lines[1]


def test_rosetta_executable_root_database_and_molfile_validation(tmp_path: Path) -> None:
    bin_dir = tmp_path / "rosetta bin"
    db = tmp_path / "database"
    bin_dir.mkdir()
    db.mkdir()
    exe = bin_dir / "score_jd2"
    exe.write_text("#!/bin/sh\necho rosetta\n", encoding="utf-8")
    exe.chmod(0o755)
    molfile = tmp_path / "molfile_to_params.py"
    molfile.write_text("#!/bin/sh\necho molfile\n", encoding="utf-8")
    molfile.chmod(0o755)
    code = """
from external_dependencies import resolve_rosetta_bin, resolve_rosetta_database, resolve_molfile_to_params
print(resolve_rosetta_bin(required=True).status)
print(resolve_rosetta_database(required=True).status)
print(resolve_molfile_to_params(required=True).status)
"""
    result = run_python(code, {"ROSETTA_BIN": str(bin_dir), "ROSETTA_DATABASE": str(db), "MOLFILE_TO_PARAMS": str(molfile)})
    assert result.returncode == 0, result.stderr
    assert result.stdout.splitlines() == ["PASS", "PASS", "PASS"]


def test_rosetta_dependent_mode_fails_actionably_when_missing(tmp_path: Path) -> None:
    code = """
from membraneforger_workflow import load_config, check_stage4
from pathlib import Path
cfg = load_config(Path('config/workflow.example.yaml'))
cfg['stage4']['parameter_generation_enabled'] = True
print(check_stage4(cfg, 'rosetta'))
"""
    result = run_python(code, {"ROSETTA_BIN": str(tmp_path / "missing"), "ROSETTA_DATABASE": str(tmp_path / "missingdb"), "MOLFILE_TO_PARAMS": str(tmp_path / "missing.py")})
    assert result.returncode == 0, result.stderr
    assert "Rosetta utilities are required" in result.stdout


def test_dependency_resolver_json_has_external_rows() -> None:
    result = subprocess.run([sys.executable, str(ROOT / "scripts" / "dependency_resolver.py"), "--json"], cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    assert result.returncode == 0, result.stderr
    rows = json.loads(result.stdout)
    names = {row["name"] for row in rows}
    assert {"DSSP", "PyRosetta", "Rosetta utilities", "Rosetta database", "molfile_to_params"} <= names


def test_stage4_resource_env_overrides_config_placeholder(tmp_path: Path) -> None:
    charmm = tmp_path / "licensed charmm36.ff"
    membrane = tmp_path / "licensed membrane toppar"
    write_compatible_stage4_resources(charmm, membrane)
    code = """
from membraneforger_workflow import load_config, check_stage4
from external_dependencies import resolve_stage4_resource_paths
from pathlib import Path
cfg = load_config(Path('config/workflow.example.yaml'))
cfg['stage4']['charmm36_required'] = True
cfg['stage4']['membrane_toppar_required'] = True
paths = resolve_stage4_resource_paths(cfg)
print(paths.charmm36_source, paths.charmm36_forcefield.name)
print(paths.membrane_toppar_source, paths.membrane_toppar.name)
print(check_stage4(cfg, 'envtest'))
"""
    result = run_python(
        code,
        {
            "MEMBRANEFORGER_CHARMM36_ROOT": str(charmm),
            "MEMBRANEFORGER_MEMBRANE_TOPPAR": str(membrane),
        },
    )
    assert result.returncode == 0, result.stderr
    assert "MEMBRANEFORGER_CHARMM36_ROOT licensed charmm36.ff" in result.stdout
    assert "MEMBRANEFORGER_MEMBRANE_TOPPAR licensed membrane toppar" in result.stdout
    assert result.stdout.splitlines()[-1] == "[]"


def test_stage4_resource_config_paths_work(tmp_path: Path) -> None:
    charmm = tmp_path / "charmm36.ff"
    membrane = tmp_path / "charmm36_membrane"
    write_compatible_stage4_resources(charmm, membrane)
    config = tmp_path / "workflow.yaml"
    config.write_text(
        f"""
stage4:
  charmm36_required: true
  membrane_toppar_required: true
  resources:
    charmm36_forcefield: {charmm}
    membrane_toppar: {membrane}
""",
        encoding="utf-8",
    )
    code = f"""
from membraneforger_workflow import load_config, check_stage4
from pathlib import Path
cfg = load_config(Path({str(config)!r}))
print(check_stage4(cfg, 'configtest'))
"""
    result = run_python(
        code,
        {"MEMBRANEFORGER_CHARMM36_ROOT": "", "MEMBRANEFORGER_MEMBRANE_TOPPAR": ""},
    )
    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == "[]"


def test_stage4_resource_preflight_reports_metadata_and_hashes(tmp_path: Path) -> None:
    charmm = tmp_path / "charmm36.ff"
    membrane = tmp_path / "toppar"
    write_compatible_stage4_resources(charmm, membrane, release="July 2022")
    code = f"""
from external_dependencies import preflight_stage4_charmm_resources
cfg = {{
    'stage4': {{
        'charmm36_required': True,
        'membrane_toppar_required': True,
        'n_terminal_patch': 'ACE',
        'c_terminal_patch': 'CT3',
        'resources': {{
            'charmm36_forcefield': {str(charmm)!r},
            'membrane_toppar': {str(membrane)!r},
        }},
    }}
}}
preflight = preflight_stage4_charmm_resources(cfg, include_file_hashes=True)
print(preflight.status)
print(preflight.metadata['compatibility_release_token'])
print(preflight.tree_hashes['charmm36_forcefield']['file_count'])
print(preflight.tree_hashes['membrane_toppar']['file_count'])
"""
    result = run_python(code, {"MEMBRANEFORGER_CHARMM36_ROOT": "", "MEMBRANEFORGER_MEMBRANE_TOPPAR": ""})
    assert result.returncode == 0, result.stderr
    lines = result.stdout.splitlines()
    assert lines[0] == "PASS"
    assert lines[1] == "jul-2022"
    assert int(lines[2]) >= 8
    assert int(lines[3]) >= 3


def test_missing_stage4_forcefield_itp_fails_clearly(tmp_path: Path) -> None:
    charmm = tmp_path / "charmm36.ff"
    membrane = tmp_path / "membrane"
    charmm.mkdir()
    write_compatible_stage4_resources(tmp_path / "complete_charmm36.ff", membrane)
    code = """
from membraneforger_workflow import load_config, check_stage4
from pathlib import Path
cfg = load_config(Path('config/workflow.example.yaml'))
cfg['stage4']['charmm36_required'] = True
cfg['stage4']['membrane_toppar_required'] = True
print(check_stage4(cfg, 'missingff'))
"""
    result = run_python(
        code,
        {
            "MEMBRANEFORGER_CHARMM36_ROOT": str(charmm),
            "MEMBRANEFORGER_MEMBRANE_TOPPAR": str(membrane),
        },
    )
    assert result.returncode == 0, result.stderr
    assert "forcefield.itp" in result.stdout


def test_missing_stage4_membrane_parameter_directory_fails_clearly(tmp_path: Path) -> None:
    charmm = tmp_path / "charmm36.ff"
    complete_membrane = tmp_path / "complete_membrane"
    write_compatible_stage4_resources(charmm, complete_membrane)
    code = """
from membraneforger_workflow import load_config, check_stage4
from pathlib import Path
cfg = load_config(Path('config/workflow.example.yaml'))
cfg['stage4']['charmm36_required'] = True
cfg['stage4']['membrane_toppar_required'] = True
print(check_stage4(cfg, 'missingmembrane'))
"""
    result = run_python(
        code,
        {
            "MEMBRANEFORGER_CHARMM36_ROOT": str(charmm),
            "MEMBRANEFORGER_MEMBRANE_TOPPAR": str(tmp_path / "missing_membrane"),
        },
    )
    assert result.returncode == 0, result.stderr
    assert "membrane topology/parameter directory" in result.stdout


def test_doctor_and_stage4_resource_resolver_select_same_env_paths(tmp_path: Path) -> None:
    charmm = tmp_path / "env_charmm36.ff"
    membrane = tmp_path / "env_membrane"
    write_compatible_stage4_resources(charmm, membrane)
    config = tmp_path / "workflow.yaml"
    config.write_text(
        """
stage4:
  charmm36_required: true
  membrane_toppar_required: true
  resources:
    charmm36_forcefield: resources/external/charmm36.ff
    membrane_toppar: resources/external/charmm36_membrane
""",
        encoding="utf-8",
    )
    code = f"""
from pathlib import Path
from membraneforger.cli import doctor_rows
from membraneforger_workflow import load_config
from external_dependencies import resolve_stage4_resource_paths
cfg_path = Path({str(config)!r})
cfg = load_config(cfg_path)
paths = resolve_stage4_resource_paths(cfg)
rows = {{row['name']: row for row in doctor_rows(cfg_path)}}
print(paths.charmm36_forcefield)
print(rows['CHARMM36 GROMACS force field']['detail'])
print(paths.membrane_toppar)
print(rows['CHARMM membrane parameter files']['detail'])
"""
    result = run_python(
        code,
        {
            "MEMBRANEFORGER_CHARMM36_ROOT": str(charmm),
            "MEMBRANEFORGER_MEMBRANE_TOPPAR": str(membrane),
        },
    )
    assert result.returncode == 0, result.stderr
    lines = result.stdout.splitlines()
    assert lines[0] in lines[1]
    assert lines[2] in lines[3]


def test_stage4_resource_preflight_rejects_unpaired_release_markers(tmp_path: Path) -> None:
    charmm = tmp_path / "charmm36.ff"
    membrane = tmp_path / "toppar"
    write_compatible_stage4_resources(charmm, membrane, release="July 2022")
    (membrane / "top_all36_prot.rtf").write_text(
        "*>>>>>>>>>>>>>>>>>>>>>>>>>> February 2026 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\nPRES ACE 0.00\nPRES CT3 0.00\n",
        encoding="utf-8",
    )
    (membrane / "par_all36m_prot.prm").write_text(
        "*>>>>>>>>>>>>>>>>>>>>>>>>>> February 2026 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n! CHARMM36m\n",
        encoding="utf-8",
    )
    code = f"""
from external_dependencies import preflight_stage4_charmm_resources
cfg = {{
    'stage4': {{
        'charmm36_required': True,
        'membrane_toppar_required': True,
        'resources': {{
            'charmm36_forcefield': {str(charmm)!r},
            'membrane_toppar': {str(membrane)!r},
        }},
    }}
}}
preflight = preflight_stage4_charmm_resources(cfg)
print(preflight.status)
print('\\n'.join(preflight.errors))
"""
    result = run_python(code, {"MEMBRANEFORGER_CHARMM36_ROOT": "", "MEMBRANEFORGER_MEMBRANE_TOPPAR": ""})
    assert result.returncode == 0, result.stderr
    assert result.stdout.splitlines()[0] == "FAIL"
    assert "compatibility is not established" in result.stdout


def test_stage4_resource_preflight_requires_toppar_ace_and_ct3(tmp_path: Path) -> None:
    charmm = tmp_path / "charmm36.ff"
    membrane = tmp_path / "toppar"
    write_compatible_stage4_resources(charmm, membrane)
    (membrane / "top_all36_prot.rtf").write_text(
        "*>>>>>>>>>>>>>>>>>>>>>>>>>> November 2018 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\nPRES ACE 0.00\n",
        encoding="utf-8",
    )
    code = f"""
from external_dependencies import preflight_stage4_charmm_resources
cfg = {{
    'stage4': {{
        'charmm36_required': True,
        'membrane_toppar_required': True,
        'resources': {{
            'charmm36_forcefield': {str(charmm)!r},
            'membrane_toppar': {str(membrane)!r},
        }},
    }}
}}
preflight = preflight_stage4_charmm_resources(cfg)
print(preflight.status)
print('\\n'.join(preflight.errors))
"""
    result = run_python(code, {"MEMBRANEFORGER_CHARMM36_ROOT": "", "MEMBRANEFORGER_MEMBRANE_TOPPAR": ""})
    assert result.returncode == 0, result.stderr
    assert result.stdout.splitlines()[0] == "FAIL"
    assert "PRES CT3" in result.stdout
