python:
  env: PYTHON_BIN
  required: true
gromacs:
  env: GMX_BIN
  required: false
martinize2:
  env: MARTINIZE2_BIN
  required: false
vermouth:
  python_module: vermouth
  required: false
insane:
  path: scripts/insane_M3_lipids_new.py
  required: true
mstool:
  python_module_path: resources/vendor/mstool
  required: false
openmm:
  python_module: openmm
  required: false
cython:
  python_module: Cython
  required: true
dssp:
  env: DSSP_BIN
  required: false
pyrosetta:
  env: PYROSETTA_PYTHON
  python_module: pyrosetta
  required: false
rosetta:
  env: ROSETTA_BIN
  required: false
rosetta_database:
  env: ROSETTA_DATABASE
  required: false
molfile_to_params:
  env: MOLFILE_TO_PARAMS
  required: false
apptainer:
  env: APPTAINER_BIN
  required: false
apptainer_image:
  env: APPTAINER_IMAGE
  required: false
